[package]
name = "ndrcraft"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "1.3.2"
cgmath = "0.18.0"
env_logger = "0.10.0"
image = "0.24.5"
log = "0.4.17"
pollster = "0.2.5"
wgpu = { version = "0.15.0", features = [ "naga" ] }
winit = "0.27.5"